export interface myEvent {
    id: string,
    title: string,
    start: Date,
    end: Date,
    entryFees: string,
    registrationLink: string,
    venue: string,
    prize1: string,
    prize2: string,
    prize3: string,
    description: string,
    personOne: string,
    personOneEmail: string,
    personOneContact: string,
    personTwo: string,
    personTwoEmail: string,
    personTwoContact: string,
    tileImagePath: string,
    bannerImagePath: string,
    phoneBannerImagePath: string,
}